import type { Edge } from "@xyflow/react";
import type {
  ComponentArea,
  ComponentItem,
  ComponentMapApp,
  ComponentMapWorkspace,
  PageNode,
} from "./types";

function component(
  id: string,
  name: string,
  kind: string,
  area: ComponentArea,
  description: string,
  filePath: string,
  propsMemo = "なし",
  stateMemo = "親ページまたは部品内で管理",
): ComponentItem {
  return {
    id,
    name,
    kind,
    area,
    description,
    propsMemo,
    stateMemo,
    filePath,
  };
}

function page(
  id: string,
  name: string,
  path: string,
  description: string,
  x: number,
  y: number,
  components: ComponentItem[],
): PageNode {
  return {
    id,
    type: "page",
    position: { x, y },
    data: { name, path, description, components },
  };
}

function edge(
  id: string,
  source: string,
  target: string,
  label: string,
): Edge {
  return {
    id,
    source,
    target,
    label,
    type: "smoothstep",
    animated: true,
  };
}

function createLearningLogApp(): ComponentMapApp {
  return {
    id: "learning-log-app",
    name: "Learning Log",
    description: "学習記録を登録し、振り返りと次の行動に活かすアプリ",
    repositoryUrl: "https://github.com/lesser-fam/learning-log-app",
    nodes: [
      page(
        "learning-log-list",
        "学習記録一覧",
        "/learning-logs",
        "登録済みの学習記録を一覧で確認する画面",
        80,
        100,
        [
          component(
            "learning-log-list-page",
            "LearningLogsPage",
            "ページ内UI",
            "main",
            "APIから一覧を取得し、読込・空・エラー・成功状態を切り替える",
            "src/app/learning-logs/page.tsx",
            "なし",
            "learningLogs, isLoading, error, retryCount",
          ),
        ],
      ),
      page(
        "learning-log-detail",
        "学習記録詳細",
        "/learning-logs/[id]",
        "選択した学習記録の全項目を確認する画面",
        500,
        100,
        [
          component(
            "learning-log-detail-page",
            "LearningLogPage",
            "ページ内UI",
            "main",
            "URLのIDを使って1件取得し、詳細と取得状態を表示する",
            "src/app/learning-logs/[id]/page.tsx",
            "params.id",
            "learningLog, isLoading, error, retryCount",
          ),
        ],
      ),
    ],
    edges: [
      edge(
        "learning-log-list-to-detail",
        "learning-log-list",
        "learning-log-detail",
        "詳細を見る",
      ),
      edge(
        "learning-log-detail-to-list",
        "learning-log-detail",
        "learning-log-list",
        "一覧へ戻る",
      ),
    ],
  };
}

function appHeader(id: string): ComponentItem {
  return component(
    id,
    "AppHeader",
    "共通ヘッダー",
    "header",
    "主要画面へのナビゲーション、モバイルメニュー、ログアウトを提供する",
    "src/components/AppHeader.tsx",
    "なし",
    "isMenuOpen, isLoggingOut",
  );
}

function pageState(id: string): ComponentItem {
  return component(
    id,
    "PageStateMessage",
    "状態表示",
    "main",
    "読み込み中・取得失敗・対象なしなど、ページ全体の状態を表示する",
    "src/components/pageStates/PageStateMessage.tsx",
    "message, variant?",
    "なし",
  );
}

function createMatchupNoteApp(): ComponentMapApp {
  const nodes: PageNode[] = [
    page(
      "matchup-home",
      "トップ",
      "/",
      "Matchup Noteの概要を伝え、登録・ログインへ案内する入口",
      0,
      180,
      [
        component(
          "home-navigation",
          "HomeNavigation",
          "ページ内UI",
          "main",
          "サービス説明と新規登録・ログインへの導線を表示する",
          "src/app/page.tsx",
          "なし",
          "なし",
        ),
      ],
    ),
    page(
      "matchup-register",
      "ユーザー登録",
      "/register",
      "名前・メールアドレス・パスワードを入力して利用を開始する",
      420,
      0,
      [
        component(
          "register-form",
          "RegisterForm",
          "ページ内フォーム",
          "main",
          "登録APIを呼び出し、入力エラーを項目ごとに表示する",
          "src/app/register/page.tsx",
          "なし",
          "fieldErrors, submit中のフォーム状態",
        ),
      ],
    ),
    page(
      "matchup-login",
      "ログイン",
      "/login",
      "登録済みユーザーがログインする",
      420,
      380,
      [
        component(
          "login-form",
          "LoginForm",
          "ページ内フォーム",
          "main",
          "認証APIを呼び出し、成功時にパーティ一覧へ移動する",
          "src/app/login/page.tsx",
          "なし",
          "fieldErrors, submit中のフォーム状態",
        ),
      ],
    ),
    page(
      "matchup-parties",
      "パーティ一覧",
      "/parties",
      "登録したパーティの一覧を確認し、作成や詳細表示へ進む",
      840,
      180,
      [
        appHeader("parties-app-header"),
        component(
          "party-list",
          "PartyList",
          "ページ内一覧",
          "main",
          "取得したパーティをカードとして並べ、詳細へのリンクを表示する",
          "src/app/parties/page.tsx",
          "parties: Party[]",
          "parties, isLoading",
        ),
        component(
          "parties-rule-badge",
          "PartyRuleBadge",
          "ルール表示",
          "main",
          "各パーティに適用される対戦ルールをバッジで示す",
          "src/features/pokemonRules/PartyRuleBadge.tsx",
          "rule",
          "なし",
        ),
      ],
    ),
    page(
      "matchup-help",
      "ヘルプ",
      "/help",
      "アプリの基本的な利用手順と補助機能への導線を確認する",
      840,
      620,
      [
        appHeader("help-app-header"),
        component(
          "help-guide",
          "HelpGuide",
          "ページ内ガイド",
          "main",
          "パーティ登録から選出・振り返りまでの流れを説明する",
          "src/app/help/page.tsx",
          "なし",
          "なし",
        ),
      ],
    ),
    page(
      "matchup-party-create",
      "パーティ作成",
      "/parties/create",
      "パーティ名と対戦ルールを入力して新しいパーティを登録する",
      1260,
      -260,
      [
        appHeader("party-create-app-header"),
        component(
          "party-create-form",
          "PartyCreateForm",
          "ページ内フォーム",
          "main",
          "パーティ情報を登録し、成功時に作成したパーティ詳細へ進む",
          "src/app/parties/create/page.tsx",
          "なし",
          "fieldErrors, 入力値",
        ),
      ],
    ),
    page(
      "matchup-party-detail",
      "パーティ詳細",
      "/parties/[partyId]",
      "パーティ構成、基本選出、テンプレート、対戦ログ、履歴をまとめて確認する中心画面",
      1260,
      180,
      [
        appHeader("party-detail-app-header"),
        pageState("party-detail-page-state"),
        component(
          "party-detail-header",
          "PartyDetailHeader",
          "詳細ヘッダー",
          "header",
          "パーティ名・ルールと編集、バージョン作成、削除操作を表示する",
          "src/features/parties/components/PartyDetailHeader.tsx",
          "party, isDeletingParty, onDeleteParty",
        ),
        component(
          "party-detail-navigation",
          "PartyDetailNavigationLinks",
          "機能ナビゲーション",
          "main",
          "対戦前選出、選出練習、相手テンプレート、技管理へ案内する",
          "src/features/parties/components/PartyDetailNavigationLinks.tsx",
          "partyId",
          "なし",
        ),
        component(
          "registered-party-pokemon",
          "RegisteredPartyPokemonSection",
          "登録ポケモン一覧",
          "main",
          "現在のパーティに登録されたポケモンと追加・削除操作を表示する",
          "src/features/parties/components/RegisteredPartyPokemonSection.tsx",
          "partyId, currentPokemonList, pokemonList, partyPokemonLimit, 削除状態とhandler",
        ),
        component(
          "suggested-selection",
          "SuggestedSelectionSection",
          "基本選出",
          "main",
          "パーティ情報をもとにおすすめの基本選出を表示する",
          "src/features/parties/components/SuggestedSelectionSection.tsx",
          "suggestedSelection, currentPokemonCount, selectionPokemonLimit, 保存状態とhandler, pokemonList",
        ),
        component(
          "saved-selection-templates",
          "SavedSelectionTemplatesSection",
          "選出テンプレート一覧",
          "main",
          "保存済みの選出テンプレートを表示し、編集・削除へつなぐ",
          "src/features/parties/components/SavedSelectionTemplatesSection.tsx",
          "partyId, selectionTemplates, onDeleteSelectionTemplate, pokemonList",
        ),
        component(
          "battle-log-summary",
          "BattleLogSummarySection",
          "対戦集計",
          "main",
          "対戦ログから勝敗や選出傾向を集計して表示する",
          "src/features/parties/components/BattleLogSummarySection.tsx",
          "battleLogSummary, partyPokemonList, pokemonList, title?, description?",
        ),
        component(
          "battle-log-list",
          "BattleLogListSection",
          "対戦ログ一覧",
          "main",
          "対戦記録を一覧表示し、編集対象を選べるようにする",
          "src/features/parties/components/BattleLogListSection.tsx",
          "partyId, title, description, battleLogs, pokemonList, 削除状態とhandler",
        ),
        component(
          "party-version-history",
          "PartyVersionHistory",
          "履歴一覧",
          "main",
          "パーティの過去バージョンを時系列で確認する",
          "src/features/parties/components/PartyVersionHistory.tsx",
          "versions, findPokemonMaster",
        ),
      ],
    ),
    page(
      "matchup-party-edit",
      "パーティ編集",
      "/parties/[partyId]/edit",
      "パーティ名・説明・対戦ルールなどの基本情報を変更する",
      1680,
      -680,
      [
        appHeader("party-edit-app-header"),
        component(
          "party-edit-form",
          "PartyEditForm",
          "ページ内フォーム",
          "main",
          "既存値を初期表示し、更新APIの入力エラーと成功遷移を扱う",
          "src/app/parties/[partyId]/edit/page.tsx",
          "params.partyId",
          "party, fieldErrors, 入力値",
        ),
      ],
    ),
    page(
      "matchup-party-version-create",
      "新バージョン作成",
      "/parties/[partyId]/versions/create",
      "現在の構成をもとにポケモンを入れ替え、新しいパーティ履歴を作る",
      1680,
      -220,
      [
        appHeader("party-version-app-header"),
        pageState("party-version-page-state"),
        component(
          "version-rule-badge",
          "PartyRuleBadge",
          "ルール表示",
          "header",
          "編集対象パーティの適用ルールを表示する",
          "src/features/pokemonRules/PartyRuleBadge.tsx",
          "rule",
          "なし",
        ),
        component(
          "editable-pokemon-card-list",
          "EditablePokemonCardList",
          "編集対象一覧",
          "main",
          "新バージョンに含めるポケモンの並びと選択状態を表示する",
          "src/features/partyVersions/components/EditablePokemonCardList.tsx",
          "pokemonList, selectedIndex, onSelectほか",
        ),
        component(
          "editable-pokemon-editor",
          "EditablePokemonEditorSection",
          "ポケモン編集",
          "main",
          "選択中ポケモンの型・技・努力値・タグなどを編集する",
          "src/features/partyVersions/components/EditablePokemonEditorSection.tsx",
          "editablePokemon, roleTags, natureListほか",
        ),
        component(
          "editable-pokemon-search",
          "EditablePokemonSearchSection",
          "ポケモン検索",
          "main",
          "マスターデータから追加するポケモンを検索・選択する",
          "src/features/partyVersions/components/EditablePokemonSearchSection.tsx",
          "pokemonList, selectedPokemon, onSelect",
        ),
      ],
    ),
    page(
      "matchup-party-pokemon-create",
      "パーティポケモン追加",
      "/parties/[partyId]/pokemon/create",
      "ポケモンを検索し、特性・技・努力値・役割タグを設定して追加する",
      1680,
      240,
      [
        appHeader("pokemon-create-app-header"),
        pageState("pokemon-create-page-state"),
        component(
          "pokemon-create-rule-badge",
          "PartyRuleBadge",
          "ルール表示",
          "header",
          "努力値などの入力上限に関係する対戦ルールを表示する",
          "src/features/pokemonRules/PartyRuleBadge.tsx",
          "rule",
          "なし",
        ),
        component(
          "party-pokemon-search-section",
          "PartyPokemonSearchSection",
          "ポケモン検索",
          "main",
          "名前・タイプから登録対象のポケモンを探す",
          "src/features/partyPokemon/components/PartyPokemonSearchSection.tsx",
          "pokemonList, selectedPokemon, onSelectほか",
        ),
        component(
          "selected-pokemon-preview",
          "SelectedPokemonPreviewCard",
          "選択内容プレビュー",
          "main",
          "選択したポケモンの画像・名前・タイプを確認する",
          "src/features/partyPokemon/components/SelectedPokemonPreviewCard.tsx",
          "pokemon",
        ),
        component(
          "party-pokemon-build-section",
          "PartyPokemonBuildSection",
          "育成内容フォーム",
          "main",
          "特性・性格・技・努力値・役割タグなどをまとめて入力する",
          "src/features/partyPokemon/components/PartyPokemonBuildSection.tsx",
          "form, rule, masterData, handlers",
          "親のusePartyPokemonFormが入力状態を管理",
        ),
      ],
    ),
    page(
      "matchup-battle-preview",
      "対戦前選出",
      "/parties/[partyId]/battle-preview",
      "相手のポケモンを入力し、相性分析とおすすめ選出を確認する",
      1680,
      700,
      [
        pageState("battle-preview-page-state"),
        component(
          "battle-preview-header",
          "BattlePreviewHeader",
          "画面ヘッダー",
          "header",
          "パーティ詳細へ戻る導線と対戦前選出の説明を表示する",
          "src/features/battlePreview/components/BattlePreviewHeader.tsx",
          "partyId",
          "なし",
        ),
        component(
          "own-party-column",
          "OwnPartyColumn",
          "自分パーティ",
          "sidebar",
          "自分のパーティと選出中のポケモンを表示する",
          "src/features/battlePreview/components/OwnPartyColumn.tsx",
          "partyPokemonList, selectedIds, handlers",
        ),
        component(
          "opponent-search-section",
          "OpponentPokemonSearchSection",
          "相手検索",
          "main",
          "相手パーティのポケモンを検索して追加する",
          "src/features/battlePreview/components/OpponentPokemonSearchSection.tsx",
          "pokemonList, opponentList, handlers",
        ),
        component(
          "matchup-suggestions",
          "MatchupSelectionSuggestionsSection",
          "おすすめ選出",
          "main",
          "基本選出と相手情報から候補となる選出パターンを提示する",
          "src/features/battlePreview/components/MatchupSelectionSuggestionsSection.tsx",
          "suggestions, pokemonList, selectedIds",
        ),
        component(
          "stat-comparison-mode",
          "StatComparisonModeSection",
          "比較条件",
          "main",
          "素早さなどの実数値比較モードを選択する",
          "src/features/battlePreview/components/StatComparisonModeSection.tsx",
          "mode, onChange",
        ),
        component(
          "battle-log-navigation",
          "BattleLogCreateNavigationSection",
          "次画面導線",
          "footer",
          "相手と自分の選出をクエリにして対戦ログ作成へ引き継ぐ",
          "src/features/battlePreview/components/BattleLogCreateNavigationSection.tsx",
          "battleLogCreateHref, canCreateBattleLog, counts",
        ),
        component(
          "battle-preview-detail-analysis",
          "BattlePreviewDetailAnalysisSection",
          "詳細分析",
          "main",
          "攻撃・防御相性など、選出判断に使う詳しい分析を表示する",
          "src/features/battlePreview/components/BattlePreviewDetailAnalysisSection.tsx",
          "analysis結果, pokemonList",
        ),
        component(
          "opponent-party-column",
          "OpponentPartyColumn",
          "相手パーティ",
          "sidebar",
          "入力した相手ポケモンと型・道具・能力情報を表示する",
          "src/features/battlePreview/components/OpponentPartyColumn.tsx",
          "opponentList, renderPokemonCard",
        ),
      ],
    ),
    page(
      "matchup-selection-practice",
      "選出練習モード",
      "/parties/[partyId]/selection-practice",
      "ランダム・対戦履歴・テンプレートの相手を使って選出判断を練習する",
      1680,
      1160,
      [
        component(
          "selection-practice-workspace",
          "SelectionPracticeWorkspace",
          "ページ内UI",
          "main",
          "相手生成、自分の選出、答え合わせ、採点の一連の状態を管理する",
          "src/app/parties/[partyId]/selection-practice/page.tsx",
          "params.partyId",
          "party, opponentList, selectedIds, generationMode, answerState",
        ),
        component(
          "practice-battle-pokemon-card",
          "BattlePokemonCard",
          "ポケモンカード",
          "main",
          "練習対象ポケモンの情報と選択操作を表示する",
          "src/features/battlePreview/components/BattlePokemonCard.tsx",
          "pokemon, selected, onClickほか",
        ),
        component(
          "practice-mega-toggle",
          "MegaFormToggle",
          "形態切替",
          "main",
          "メガシンカ形態を想定した表示へ切り替える",
          "src/features/battlePreview/components/MegaFormToggle.tsx",
          "enabled, onChange",
        ),
        component(
          "practice-pokemon-search",
          "PokemonSearchSelector",
          "ポケモン検索",
          "main",
          "手動で相手ポケモンを検索・選択する",
          "src/features/partyPokemon/components/PokemonSearchSelector.tsx",
          "pokemonList, selectedPokemon, onSelectほか",
        ),
        component(
          "practice-opponent-column",
          "OpponentPartyColumn",
          "相手パーティ",
          "sidebar",
          "生成された相手パーティを一覧で表示する",
          "src/features/battlePreview/components/OpponentPartyColumn.tsx",
          "opponentList, renderPokemonCard",
        ),
        component(
          "ability-item-tooltips",
          "AbilityTooltip / ItemTooltip",
          "補足表示",
          "main",
          "特性候補や持ち物の説明をホバー・フォーカスで確認する",
          "src/features/battlePreview/components/AbilityTooltip.tsx / ItemTooltip.tsx",
          "abilityまたはitem情報",
          "開閉状態",
        ),
      ],
    ),
    page(
      "matchup-opponent-templates",
      "相手パーティテンプレート",
      "/opponent-party-templates",
      "よく対戦する相手構築を登録・編集し、選出練習で再利用する",
      2100,
      1160,
      [
        appHeader("opponent-template-app-header"),
        component(
          "opponent-template-manager",
          "OpponentPartyTemplateManager",
          "ページ内管理UI",
          "main",
          "テンプレート一覧、入力フォーム、管理者操作をまとめて扱う",
          "src/app/opponent-party-templates/page.tsx",
          "query.partyId",
          "templates, selectedPokemonList, selectedRule, sourceParty",
        ),
        component(
          "opponent-template-search",
          "PokemonSearchSelector",
          "ポケモン検索",
          "main",
          "テンプレートへ追加するポケモンを検索する",
          "src/features/partyPokemon/components/PokemonSearchSelector.tsx",
          "pokemonList, selectedPokemon, onSelectほか",
        ),
      ],
    ),
    page(
      "matchup-common-moves",
      "よく使われる技",
      "/common-moves",
      "ポケモンごとの主要な技を確認し、管理者は登録・CSV取込を行う",
      2100,
      1620,
      [
        appHeader("common-moves-app-header"),
        component(
          "common-moves-manager",
          "CommonMovesManager",
          "ページ内管理UI",
          "main",
          "ポケモン選択、技一覧、管理者用編集・CSV取込を扱う",
          "src/app/common-moves/page.tsx",
          "query.partyId",
          "selectedPokemon, commonMoves, selectedRule, csvFile",
        ),
        component(
          "common-moves-pokemon-search",
          "PokemonSearchSelector",
          "ポケモン検索",
          "main",
          "技を確認・登録する対象のポケモンを検索する",
          "src/features/partyPokemon/components/PokemonSearchSelector.tsx",
          "pokemonList, selectedPokemon, onSelectほか",
        ),
        component(
          "common-moves-selector",
          "MoveSelector",
          "技選択",
          "main",
          "マスターデータから登録する技を検索・選択する",
          "src/features/master/components/MoveSelector.tsx",
          "value, options, onChangeほか",
        ),
      ],
    ),
    page(
      "matchup-battle-log-create",
      "対戦ログ作成",
      "/parties/[partyId]/battle-logs/create",
      "対戦前選出から引き継いだ相手と自分の選出をもとに対戦結果を記録する",
      2100,
      700,
      [
        appHeader("battle-log-create-app-header"),
        component(
          "battle-log-create-form",
          "BattleLogForm",
          "対戦記録フォーム",
          "main",
          "選出、勝敗、反省などを入力し、新しい対戦ログを登録する",
          "src/features/battleLogs/components/BattleLogForm.tsx",
          "party, pokemonList, opponentPokemonPairs, initialValues, submitLabel, submittingLabel, onSubmit",
          "フォーム入力値と送信状態",
        ),
      ],
    ),
    page(
      "matchup-battle-log-edit",
      "対戦ログ編集",
      "/parties/[partyId]/battle-logs/[battleLogId]/edit",
      "保存済みの対戦ログを読み込み、内容を修正する",
      2100,
      240,
      [
        appHeader("battle-log-edit-app-header"),
        component(
          "battle-log-edit-form",
          "BattleLogForm",
          "対戦記録フォーム",
          "main",
          "既存値を初期表示し、更新APIへ編集内容を送信する",
          "src/features/battleLogs/components/BattleLogForm.tsx",
          "party, pokemonList, opponentPokemonPairs, initialValues, submitLabel, submittingLabel, onSubmit",
          "フォーム入力値と送信状態",
        ),
      ],
    ),
    page(
      "matchup-selection-template-edit",
      "選出テンプレート編集",
      "/parties/[partyId]/selection-templates/[selectionTemplateId]/edit",
      "保存した基本選出テンプレートの名称・選出順・条件を修正する",
      2100,
      -220,
      [
        appHeader("selection-template-edit-app-header"),
        component(
          "selection-template-edit-form",
          "SelectionTemplateEditForm",
          "ページ内フォーム",
          "main",
          "テンプレートの既存値を編集し、更新後にパーティ詳細へ戻る",
          "src/app/parties/[partyId]/selection-templates/[selectionTemplateId]/edit/page.tsx",
          "params.partyId, params.selectionTemplateId",
          "party, selectionTemplate, pokemonList, 入力値",
        ),
      ],
    ),
  ];

  const edges: Edge[] = [
    edge("home-register", "matchup-home", "matchup-register", "新規登録"),
    edge("home-login", "matchup-home", "matchup-login", "ログイン"),
    edge("register-parties", "matchup-register", "matchup-parties", "登録成功"),
    edge("login-parties", "matchup-login", "matchup-parties", "ログイン成功"),
    edge("parties-create", "matchup-parties", "matchup-party-create", "パーティ作成"),
    edge("parties-detail", "matchup-parties", "matchup-party-detail", "パーティを選択"),
    edge("parties-help", "matchup-parties", "matchup-help", "ヘルプ"),
    edge("help-parties", "matchup-help", "matchup-parties", "パーティ一覧"),
    edge("help-opponent", "matchup-help", "matchup-opponent-templates", "テンプレート管理"),
    edge("help-moves", "matchup-help", "matchup-common-moves", "技管理"),
    edge("create-detail", "matchup-party-create", "matchup-party-detail", "作成成功"),
    edge("detail-edit", "matchup-party-detail", "matchup-party-edit", "基本情報を編集"),
    edge("edit-detail", "matchup-party-edit", "matchup-party-detail", "更新・戻る"),
    edge("detail-version", "matchup-party-detail", "matchup-party-version-create", "新バージョン"),
    edge("version-detail", "matchup-party-version-create", "matchup-party-detail", "作成成功"),
    edge("detail-pokemon", "matchup-party-detail", "matchup-party-pokemon-create", "ポケモン追加"),
    edge("pokemon-detail", "matchup-party-pokemon-create", "matchup-party-detail", "追加成功"),
    edge("detail-preview", "matchup-party-detail", "matchup-battle-preview", "対戦前選出"),
    edge("preview-detail", "matchup-battle-preview", "matchup-party-detail", "詳細へ戻る"),
    edge("preview-log-create", "matchup-battle-preview", "matchup-battle-log-create", "選出を引き継ぐ"),
    edge("log-create-detail", "matchup-battle-log-create", "matchup-party-detail", "登録成功"),
    edge("detail-log-edit", "matchup-party-detail", "matchup-battle-log-edit", "対戦ログ編集"),
    edge("log-edit-detail", "matchup-battle-log-edit", "matchup-party-detail", "更新成功"),
    edge("detail-practice", "matchup-party-detail", "matchup-selection-practice", "選出練習"),
    edge("practice-detail", "matchup-selection-practice", "matchup-party-detail", "詳細へ戻る"),
    edge("practice-preview", "matchup-selection-practice", "matchup-battle-preview", "対戦前選出へ"),
    edge("practice-opponent", "matchup-selection-practice", "matchup-opponent-templates", "テンプレート管理"),
    edge("detail-opponent", "matchup-party-detail", "matchup-opponent-templates", "相手テンプレート"),
    edge("opponent-detail", "matchup-opponent-templates", "matchup-party-detail", "詳細へ戻る"),
    edge("opponent-practice", "matchup-opponent-templates", "matchup-selection-practice", "練習へ戻る"),
    edge("detail-moves", "matchup-party-detail", "matchup-common-moves", "よく使われる技"),
    edge("moves-detail", "matchup-common-moves", "matchup-party-detail", "詳細へ戻る"),
    edge("detail-template-edit", "matchup-party-detail", "matchup-selection-template-edit", "テンプレート編集"),
    edge("template-edit-detail", "matchup-selection-template-edit", "matchup-party-detail", "更新・戻る"),
  ];

  return {
    id: "matchup-note",
    name: "Matchup Note",
    description:
      "ポケモン対戦初心者がパーティ・選出・対戦ログを記録し、次の判断に活かすアプリ",
    repositoryUrl: "https://github.com/lesser-fam/pokemon-note-app",
    nodes,
    edges,
  };
}

export function createInitialComponentMapWorkspace(): ComponentMapWorkspace {
  const apps = [createLearningLogApp(), createMatchupNoteApp()];

  return {
    version: 2,
    activeAppId: apps[0].id,
    apps,
  };
}
